name: ZO_Estim_PZO
sigma: 0.01
n_sample: 1
signsgd: false

scale: null
# scale: sqrt_fim
# scale: dim

# ZO_trainable_layers_list: ['GCPBertSubLayer2', 'GCPBertSubLayer3', 'GCPBertSubLayer4', 'GCPBertSubLayer5']
ZO_trainable_layers_list: ['GCPBertSubLayer1', 'GCPBertSubLayer2', 'GCPBertSubLayer3', 'GCPBertSubLayer4', 'GCPBertSubLayer5']

estimate_method: forward
# sample_method: gaussian
sample_method: bernoulli

quantized: false
normalize_perturbation: false
en_param_commit: false

##### modelwise pseudo-ZO node perturbation #####
# actv_perturb_block_idx_list: all
actv_perturb_block_idx_list: [0,]
param_perturb_block_idx_list: null

obj_fn_type: LM_PZO
en_layerwise_perturbation: false
en_partial_forward: false
en_wp_np_mixture: false

en_pseudo_ZO: true
pzo_momentum: 0.99
pzo_detach_idx: -1

estimate_method: forward